#!/bin/sh
# forward the command to the Docker container
script=`basename $0`
sudo docker run -v /:/hroot -v $HOME/.ndless:/home/ndless/.ndless -w /hroot$(pwd) -u ndless -i -e HOME=/home/ndless ndless/ndless-sdk $script "$@"

