/* Each entry matches a symbol in syscalls.h.
 * This file is generated by mksyscalls.sh from the IDC file, please DO NOT EDIT MANUALLY. */
unsigned syscalls_light_cascx_3_6_0[] = {
	  0X103FD2C8
	, 0X103FD46C
	, 0X103FCB3C
	, 0X103FDC6C
	, 0X103F7860
	, 0X104053C0
	, 0X103FEEE4
	, 0X103FED28
	, 0X103FF168
	, 0X10403D28
	, 0X10404EBC
	, 0X103FEF34
	, 0X10402C00
	, 0X103FEE8C
	, 0X103FF290
	, 0X103F77EC
	, 0X103FEFF8
};
